[package]
name = "hello"
version = "0.1.0"
edition = "2024"
publish = false

[lints.clippy]
pedantic = { level = "warn", priority = -1 }

[workspace]

[workspace.metadata.dylint]
libraries = [
    { git = "https://github.com/LongTermSupport/rust-qa-ci", rev = "62bb8ba2ba74aa5c80281b44e43f6217314feed2", pattern = "lints/rqaci_lints" },
]
