name: ruby

on: [push, workflow_dispatch]

permissions:
  contents: read

jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '4.0'
          bundler-cache: true
          working-directory: ruby
      - run: bash ci/run-language.bash ruby
