name: rust
on: [push, workflow_dispatch]
permissions:
  contents: read
jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - run: rustup --version && rustup toolchain install
        working-directory: rust
      - run: bash ci/run-language.bash rust
